require('dotenv').config()
console.log(process.env.REDIS_URL)
console.log(process.env.DATABASE_URL)
require('./auth');
require('./rides');
require('./likes');
require('./user');
require('./users');
require('./social');