version: '3'

services:
  web:
    image: ericdo/ppz_web:latest
    container_name: ppz_web
    ports:
      - "8080:80"
    networks:
      - app-network

  nodejs:
    image: ericdo/ppz_node:latest
    container_name: ppz_node
    restart: unless-stopped
    ports:
      - "80:3001"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: ppz_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=student
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    ports:
      - "5431:5432"

  redis:
    image: ericdo/ppz_redis:latest
    container_name: ppz_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge