version: '3'

services:
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nodejs
    container_name: ppz_node
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL
      - SECRET_TOKEN
      - NODE_ENV
    ports:
      - "80:3001"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/home/node/app/node_modules
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon server/index.js

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    # image: postgres:14
    container_name: ppz_db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    container_name: ppz_redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: